# Generated by Django 5.1.7 on 2025-03-23 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banini_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('tipo_gasto', models.CharField(choices=[('fixo', 'Fixo'), ('variavel', 'Variável')], max_length=10)),
                ('recorrencia', models.CharField(choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banini_app.fornecedor')),
            ],
        ),
    ]
